"""AuthShield Interactive & Automated Attack Simulation Script.

Executes realistic IAM threat scenarios (PRD Section 26):
  - Scenario A: 5 failed logins from 10.0.0.15 -> Triggers BRUTE_FORCE_LOGIN alert.
  - Scenario B: 2 failed logins from 10.0.0.20 -> Sub-threshold, no alert generated.
  - Scenario C: Normal user attempts admin endpoint -> 403 Forbidden + ACCESS_DENIED audit log;
                repeated attempts trigger REPEATED_UNAUTHORIZED_ACCESS.
  - Scenario D: Admin promotes user to admin -> Triggers PRIVILEGE_CHANGE alert.
  - Scenario E: Login against disabled user -> Triggers LOGIN_ATTEMPT_DISABLED_ACCOUNT alert.
"""

import sys
import os
import time

# Ensure project root is in python path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import httpx
from fastapi.testclient import TestClient
from app.main import app

# Check if external server is running, otherwise use FastAPI TestClient
LIVE_SERVER_URL = "http://127.0.0.1:8000"


def get_client():
    """Returns an HTTP client pointing either to live server or in-process TestClient."""
    try:
        response = httpx.get(f"{LIVE_SERVER_URL}/health", timeout=1.0)
        if response.status_code == 200:
            print(f"[+] Connected to live AuthShield server at {LIVE_SERVER_URL}\n")
            return httpx.Client(base_url=LIVE_SERVER_URL)
    except Exception:
        pass

    print("[*] Live server not detected on :8000. Running simulation in-process via FastAPI TestClient...\n")
    return TestClient(app)


def print_banner(title: str):
    print("=" * 70)
    print(f"  {title}")
    print("=" * 70)


def run_simulations():
    client = get_client()

    # -------------------------------------------------------------
    # Scenario A: Brute Force Attack
    # -------------------------------------------------------------
    print_banner("Scenario A: Brute Force Login Attack Simulation")
    sim_ip_a = "10.0.0.15"
    print(f"[*] Attacker IP: {sim_ip_a}")
    print(f"[*] Sending 5 consecutive invalid login attempts...")

    for i in range(1, 6):
        resp = client.post(
            "/auth/login",
            json={"email": "admin@authshield.io", "password": f"wrongpassword{i}"},
            headers={"X-Simulated-IP": sim_ip_a}
        )
        print(f"    Attempt #{i} -> HTTP {resp.status_code}: {resp.json().get('detail')}")

    # Verify if alert was generated by logging in as analyst
    analyst_login = client.post(
        "/auth/login",
        json={"email": "analyst@authshield.io", "password": "AnalystPassword123!"}
    )
    analyst_token = analyst_login.json()["access_token"]

    alerts_resp = client.get(
        "/alerts?severity=HIGH",
        headers={"Authorization": f"Bearer {analyst_token}"}
    )
    alerts = alerts_resp.json()
    bf_alert = next((a for a in alerts if a["alert_type"] == "BRUTE_FORCE_LOGIN" and a["source_ip"] == sim_ip_a), None)
    if bf_alert:
        print(f"\n[!] SUCCESS: Brute-Force Alert Triggered!")
        print(f"    Alert ID: {bf_alert['id']} | Type: {bf_alert['alert_type']} | Severity: {bf_alert['severity']}")
        print(f"    Description: {bf_alert['description']}")
    else:
        print("\n[-] Alert not found.")

    # -------------------------------------------------------------
    # Scenario B: Below-Threshold Failed Logins
    # -------------------------------------------------------------
    print("\n")
    print_banner("Scenario B: Low-Volume Failed Login Simulation (Below Threshold)")
    sim_ip_b = "10.0.0.20"
    print(f"[*] Normal user typo IP: {sim_ip_b}")
    print(f"[*] Sending 2 failed login attempts (Threshold is 5)...")

    for i in range(1, 3):
        resp = client.post(
            "/auth/login",
            json={"email": "user@authshield.io", "password": "TypoPassword"},
            headers={"X-Simulated-IP": sim_ip_b}
        )
        print(f"    Attempt #{i} -> HTTP {resp.status_code}: {resp.json().get('detail')}")

    alerts_resp_b = client.get(
        f"/alerts",
        headers={"Authorization": f"Bearer {analyst_token}"}
    )
    b_alert = next((a for a in alerts_resp_b.json() if a["source_ip"] == sim_ip_b), None)
    if not b_alert:
        print(f"\n[+] SUCCESS: No alert generated for {sim_ip_b} as expected (failed attempts < threshold).")
    else:
        print(f"[-] Unexpected alert found: {b_alert}")

    # -------------------------------------------------------------
    # Scenario C: Unauthorized Endpoint Access
    # -------------------------------------------------------------
    print("\n")
    print_banner("Scenario C: Unauthorized Access & RBAC Enforcement")
    user_login = client.post(
        "/auth/login",
        json={"email": "user@authshield.io", "password": "UserPassword123!"}
    )
    user_token = user_login.json()["access_token"]
    sim_ip_c = "192.168.1.50"

    print(f"[*] Authenticated as role 'user'. Attempting to access admin-only endpoint: GET /users")
    for i in range(1, 4):
        resp = client.get(
            "/users",
            headers={"Authorization": f"Bearer {user_token}", "X-Simulated-IP": sim_ip_c}
        )
        print(f"    Access Attempt #{i} -> HTTP {resp.status_code}: {resp.json().get('detail')}")

    # Check for repeated unauthorized access alert
    alerts_resp_c = client.get(
        "/alerts",
        headers={"Authorization": f"Bearer {analyst_token}"}
    )
    unauth_alert = next((a for a in alerts_resp_c.json() if a["alert_type"] == "REPEATED_UNAUTHORIZED_ACCESS" and a["source_ip"] == sim_ip_c), None)
    if unauth_alert:
        print(f"\n[!] SUCCESS: Repeated Unauthorized Access Alert Triggered!")
        print(f"    Alert ID: {unauth_alert['id']} | Type: {unauth_alert['alert_type']} | Severity: {unauth_alert['severity']}")
        print(f"    Description: {unauth_alert['description']}")

    # -------------------------------------------------------------
    # Scenario D: Privilege Escalation
    # -------------------------------------------------------------
    print("\n")
    print_banner("Scenario D: Privilege Escalation Alert")
    admin_login = client.post(
        "/auth/login",
        json={"email": "admin@authshield.io", "password": "AdminPassword123!"}
    )
    admin_token = admin_login.json()["access_token"]

    # Register a new dummy user to promote
    dummy_email = f"target_user_{int(time.time())}@authshield.io"
    reg_resp = client.post(
        "/auth/register",
        json={"username": f"target_{int(time.time())}", "email": dummy_email, "password": "TestPassword123!"}
    )
    target_user_id = reg_resp.json()["id"]
    print(f"[*] Admin promoting newly registered user (ID: {target_user_id}) to 'admin' role...")

    promote_resp = client.patch(
        f"/users/{target_user_id}/role",
        json={"role_name": "admin"},
        headers={"Authorization": f"Bearer {admin_token}", "X-Simulated-IP": "10.0.0.1"}
    )
    print(f"    Role update -> HTTP {promote_resp.status_code}")

    alerts_resp_d = client.get(
        "/alerts",
        headers={"Authorization": f"Bearer {analyst_token}"}
    )
    priv_alert = next((a for a in alerts_resp_d.json() if a["alert_type"] == "PRIVILEGE_CHANGE" and a["user_id"] == target_user_id), None)
    if priv_alert:
        print(f"\n[!] SUCCESS: Privilege Escalation Alert Triggered!")
        print(f"    Alert ID: {priv_alert['id']} | Type: {priv_alert['alert_type']} | Severity: {priv_alert['severity']}")
        print(f"    Description: {priv_alert['description']}")

    # -------------------------------------------------------------
    # Scenario E: Disabled Account Authentication Attempt
    # -------------------------------------------------------------
    print("\n")
    print_banner("Scenario E: Disabled Account Login Attempt")
    print("[*] Attempting authentication against known disabled user: disabled@authshield.io...")
    disabled_resp = client.post(
        "/auth/login",
        json={"email": "disabled@authshield.io", "password": "DisabledPassword123!"},
        headers={"X-Simulated-IP": "172.16.0.99"}
    )
    print(f"    Login Attempt -> HTTP {disabled_resp.status_code}: {disabled_resp.json().get('detail')}")

    alerts_resp_e = client.get(
        "/alerts",
        headers={"Authorization": f"Bearer {analyst_token}"}
    )
    disabled_alert = next((a for a in alerts_resp_e.json() if a["alert_type"] == "LOGIN_ATTEMPT_DISABLED_ACCOUNT"), None)
    if disabled_alert:
        print(f"\n[!] SUCCESS: Disabled Account Login Alert Triggered!")
        print(f"    Alert ID: {disabled_alert['id']} | Type: {disabled_alert['alert_type']} | Severity: {disabled_alert['severity']}")
        print(f"    Description: {disabled_alert['description']}")

    print("\n" + "=" * 70)
    print("  ALL SIMULATION SCENARIOS COMPLETED SUCCESSFULLY")
    print("=" * 70)


if __name__ == "__main__":
    run_simulations()
