"""Security Alert model for rule-triggered threat notifications."""

from datetime import datetime, timezone
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from app.database.connection import Base


class SecurityAlert(Base):
    """Security alert generated by the detection engine."""
    __tablename__ = "security_alerts"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False, index=True)
    alert_type = Column(String(50), nullable=False, index=True)
    severity = Column(String(20), nullable=False, index=True)  # LOW, MEDIUM, HIGH, CRITICAL
    user_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    source_ip = Column(String(50), nullable=False, index=True)
    description = Column(Text, nullable=False)
    status = Column(String(20), default="OPEN", nullable=False, index=True)  # OPEN, INVESTIGATING, RESOLVED, FALSE_POSITIVE

    user = relationship("User", back_populates="security_alerts")
