[theme]
primaryColor = "#0284c7"
backgroundColor = "#060709"
secondaryBackgroundColor = "#0b0e14"
textColor = "#e2e8f0"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
